using StandUpHero;

var settings = new Preferences();
var routine = new Routine(settings);
var monday = new DateTimeOffset(new DateTime(2026, 9, 21, 9, 0, 0, DateTimeKind.Local));
int passed = 0;
void Check(bool condition, string name) { if (!condition) throw new Exception(name); passed++; Console.WriteLine("OK " + name); }
routine.Tick(monday);
Check(routine.Active && !routine.Standing && routine.Remaining.TotalMinutes == 45, "Monday starts sitting");
Check(routine.Tick(monday.AddMinutes(45)) && routine.Standing && routine.Remaining.TotalMinutes == 15, "Transition to standing");
Check(routine.Tick(monday.AddMinutes(60)) && !routine.Standing, "Transition to sitting");
routine.Tick(monday.AddMinutes(65)); routine.TogglePause(monday.AddMinutes(65)); routine.Tick(monday.AddMinutes(90));
Check(routine.Paused && routine.Remaining.TotalMinutes == 40, "Pause freezes time");
routine.TogglePause(monday.AddMinutes(90)); routine.Tick(monday.AddMinutes(95));
Check(!routine.Paused && routine.Remaining.TotalMinutes == 35, "Resume preserves time");
routine.Skip(monday.AddMinutes(95));
Check(routine.Standing && routine.Remaining.TotalMinutes == 15, "Manual posture change");
routine.Tick(monday.AddHours(9)); Check(!routine.Active, "End of scheduled window");
routine.Tick(monday.AddDays(5)); Check(!routine.Active, "Weekend inactive");
settings.Activity = "Relaxando"; routine.Tick(monday); Check(!routine.Active, "Relax mode inactive");
settings.Activity = "Trabalhando"; routine.Tick(monday); Check(routine.Active && !routine.Standing, "Returning to work starts sitting");
routine.Tick(monday.AddHours(4)); Check(routine.Standing && routine.Remaining.TotalMinutes == 15, "Sleep recovery advances once");
settings.Slots = [new(TimeSpan.FromHours(9), TimeSpan.FromHours(12)), new(TimeSpan.FromHours(13), TimeSpan.FromHours(18))];
routine.Configure(settings); routine.Tick(monday.AddHours(3.5)); Check(!routine.Active, "Lunch break inactive");
routine.Tick(monday.AddHours(4)); Check(routine.Active && !routine.Standing, "Afternoon restarts sitting");
settings.Slots = [new(TimeSpan.FromHours(9), TimeSpan.FromHours(12)), new(TimeSpan.FromHours(11), TimeSpan.FromHours(18))];
Check(settings.WindowStart(monday.AddHours(4).LocalDateTime) == monday.LocalDateTime, "Overlapping windows merged");
settings.SittingMinutes = 0; Check(!settings.IsValid(), "Invalid durations rejected");
var legacy = System.Text.Json.JsonSerializer.Deserialize<Preferences>("{\"SittingMinutes\":30,\"Sound\":false}")!;
Check(legacy.IsValid() && legacy.SittingMinutes == 30 && !legacy.Sound && legacy.Character == "Homem", "Legacy settings retain values and receive new defaults");
var custom = new Preferences { Character = "Mulher", StandSound = "Arcade", SitSound = "Sem som" };
var restored = System.Text.Json.JsonSerializer.Deserialize<Preferences>(System.Text.Json.JsonSerializer.Serialize(custom))!;
Check(restored.IsValid() && restored.Character == "Mulher" && restored.StandSound == "Arcade" && restored.SitSound == "Sem som", "Character and separate sounds survive persistence");
restored.StandSound = "missing"; Check(!restored.IsValid(), "Unknown sound rejected");
Check(legacy.VisualAlerts && legacy.VisualAlertSeconds == 12, "Old preferences enable the visual reminder with a twelve-second default");
var visual = new Preferences { VisualAlerts = false, VisualAlertSeconds = 20 };
var visualSaved = System.Text.Json.JsonSerializer.Deserialize<Preferences>(System.Text.Json.JsonSerializer.Serialize(visual))!;
Check(!visualSaved.VisualAlerts && visualSaved.VisualAlertSeconds == 20 && visualSaved.WithDefaultRoutine().VisualAlertSeconds == 20, "Visual preferences persist and survive routine reset");
visualSaved.VisualAlertSeconds = 0; Check(!visualSaved.IsValid(), "Invalid visual duration rejected");
var oldGaming = System.Text.Json.JsonSerializer.Deserialize<Preferences>("{\"Activity\":\"Jogando\",\"SittingMinutes\":32}")!;
Check(oldGaming.IsValid() && oldGaming.Activity == "Relaxando" && oldGaming.SittingMinutes == 32, "Gaming preferences migrate to Relaxing without discarding settings");
Check(legacy.SuggestRelaxing && legacy.IdleMinutes == 10, "Legacy settings receive conservative idle defaults");
var idleSettings = new Preferences { SuggestRelaxing = false, IdleMinutes = 25 };
var idleSaved = System.Text.Json.JsonSerializer.Deserialize<Preferences>(System.Text.Json.JsonSerializer.Serialize(idleSettings))!;
Check(!idleSaved.SuggestRelaxing && idleSaved.WithDefaultRoutine().IdleMinutes == 25, "Idle preferences persist and survive routine reset");
idleSaved.IdleMinutes = 0; Check(!idleSaved.IsValid(), "Invalid inactivity threshold rejected");
var policy = new IdleSuggestionPolicy();
bool Observe(double idleMinutes, double nowMinutes, bool allow = true) => policy.Observe(TimeSpan.FromMinutes(idleMinutes), TimeSpan.FromMinutes(nowMinutes), 10, allow);
Check(!Observe(9, 9) && !Observe(0, 9.1), "Short gaps do not trigger a suggestion");
Check(!Observe(10, 10) && !Observe(15, 15), "Remaining away does not trigger or repeat suggestions");
Check(Observe(0, 15.1), "One suggestion appears on return after the idle threshold");
Check(!Observe(0, 16), "Continued activity does not repeat suggestions");
Check(!Observe(10, 26) && !Observe(0, 26.1), "Thirty-minute cooldown suppresses repeated breaks");
Check(!Observe(10, 46) && Observe(0, 46.1), "A new break after the cooldown can prompt once");
Check(!Observe(10, 80) && !Observe(0, 80.1, false) && !Observe(0, 81), "Busy UI discards a suggestion instead of displaying it later");
Observe(10, 100); policy.ClearObservation(); Check(!Observe(0, 101), "Disabling or changing activity clears the idle episode");
Observe(10, 120); Check(!policy.Observe(null, TimeSpan.FromMinutes(121), 10, true) && !Observe(0, 122), "Read failures discard incomplete observations");
Check(IdleDetection.FromTicks(5, uint.MaxValue - 4) == TimeSpan.FromMilliseconds(10), "Input timestamp handles 32-bit rollover");
Check(IdleDetection.FromTicks(100, 101) is null, "Inconsistent future input timestamp is ignored");
Check(!legacy.StartWithWindows && legacy.PauseOnLock, "Windows startup defaults off; lock pause defaults on");
var systemPreferences = new Preferences { StartWithWindows = true, PauseOnLock = false };
var systemSaved = System.Text.Json.JsonSerializer.Deserialize<Preferences>(System.Text.Json.JsonSerializer.Serialize(systemPreferences))!;
Check(systemSaved.StartWithWindows && !systemSaved.PauseOnLock && systemSaved.WithDefaultRoutine().StartWithWindows, "System options persist and survive routine reset");
var deferred = new Routine(new Preferences()); deferred.Tick(monday);
Check(!deferred.Snooze(monday.AddMinutes(1)), "Snooze requires a real transition");
deferred.Tick(monday.AddMinutes(45));
Check(deferred.Snooze(monday.AddMinutes(45.5)) && !deferred.Standing && deferred.Remaining.TotalMinutes == 5, "Snooze returns to previous posture for exactly five minutes");
Check(!deferred.Snooze(monday.AddMinutes(46)), "Double snooze cannot reverse the posture again");
Check(deferred.Settings.SittingMinutes == 45 && deferred.Settings.StandingMinutes == 15, "Snooze never edits saved durations");
Check(!deferred.Tick(monday.AddMinutes(50.49)) && deferred.Tick(monday.AddMinutes(50.5)) && deferred.Standing && deferred.Remaining.TotalMinutes == 15, "Snooze repeats the transition and starts the full standing interval");
deferred.Tick(monday.AddMinutes(65.5));
Check(deferred.Snooze(monday.AddMinutes(66)) && deferred.Standing, "Sitting reminder can also be deferred");
Check(deferred.Tick(monday.AddMinutes(71)) && !deferred.Standing && deferred.Remaining.TotalMinutes == 45, "Deferred sitting starts the full sitting interval");
var lockedRoutine = new Routine(new Preferences()); lockedRoutine.Tick(monday);
lockedRoutine.SetSessionLocked(true, monday.AddMinutes(10));
Check(lockedRoutine.Paused && lockedRoutine.AwaitingResume && lockedRoutine.Remaining.TotalMinutes == 35, "Lock freezes the remaining time");
Check(!lockedRoutine.Tick(monday.AddMinutes(70)) && lockedRoutine.Remaining.TotalMinutes == 35, "No transitions occur while locked");
lockedRoutine.SetSessionLocked(false, monday.AddMinutes(80));
Check(lockedRoutine.Paused && lockedRoutine.AwaitingResume && lockedRoutine.Remaining.TotalMinutes == 35, "Unlock waits for explicit resume");
lockedRoutine.TogglePause(monday.AddMinutes(90)); lockedRoutine.Tick(monday.AddMinutes(91));
Check(!lockedRoutine.Paused && !lockedRoutine.AwaitingResume && lockedRoutine.Remaining.TotalMinutes == 34, "Resume continues exactly where lock interrupted");
lockedRoutine.TogglePause(monday.AddMinutes(92));
lockedRoutine.SetSessionLocked(true, monday.AddMinutes(93)); lockedRoutine.SetSessionLocked(false, monday.AddMinutes(94));
Check(lockedRoutine.Paused && !lockedRoutine.AwaitingResume, "Manual pause is preserved without a resume prompt");
lockedRoutine.SetSessionLocked(true, monday.AddMinutes(95)); lockedRoutine.SetSessionLocked(false, monday.AddHours(10));
Check(!lockedRoutine.Active && !lockedRoutine.AwaitingResume, "Unlock outside the schedule clears the expired period");
var optOut = new Routine(new Preferences { PauseOnLock = false }); optOut.Tick(monday); optOut.SetSessionLocked(true, monday.AddMinutes(1)); optOut.Tick(monday.AddMinutes(2));
Check(!optOut.Paused && optOut.Remaining.TotalMinutes == 43, "Lock pause can be disabled");
var acrossWindows = new Routine(new Preferences { Slots = [new(TimeSpan.FromHours(9), TimeSpan.FromHours(12)), new(TimeSpan.FromHours(13), TimeSpan.FromHours(18))] });
acrossWindows.Tick(monday); acrossWindows.SetSessionLocked(true, monday.AddMinutes(1)); acrossWindows.SetSessionLocked(false, monday.AddHours(4));
Check(acrossWindows.Paused && acrossWindows.AwaitingResume && acrossWindows.Remaining.TotalMinutes == 45, "Unlock in a new window offers a fresh paused interval");
var postponedLock = new Routine(new Preferences()); postponedLock.Tick(monday); postponedLock.Tick(monday.AddMinutes(45)); postponedLock.Snooze(monday.AddMinutes(45));
postponedLock.SetSessionLocked(true, monday.AddMinutes(47)); postponedLock.SetSessionLocked(false, monday.AddMinutes(60));
Check(postponedLock.Paused && postponedLock.Snoozed && postponedLock.Remaining.TotalMinutes == 3, "Lock also freezes a snoozed reminder");
postponedLock.TogglePause(monday.AddMinutes(60));
Check(postponedLock.Tick(monday.AddMinutes(63)) && postponedLock.Standing && postponedLock.Remaining.TotalMinutes == 15, "Resumed snooze leads to a full posture interval");
Console.WriteLine($"{passed} checks passed.");
